name: Metrics
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: rashidwassan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_stargazers: yes
